name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Restore PHP build cache
        id: php-build-cache
        uses: actions/cach@v2
        with:
          path: "./bin"
          key: "php-build-${{ hashFiles('./build/php/compile.sh') }}"
          restore-keys: "php-build-"

      - name: Compile PHP
        if: steps.php-build-cache.outputs.cache-hit != 'true'
        run: |
          ./build/php/compile.sh -j8 -f #we don't need additional extensions right now
          export PATH=$(pwd)/bin/php7/bin:$PATH

      - name: Install Composer
        run: curl -sS https://getcomposer.org/installer | php

      - name: Install Composer dependencies
        run: php composer.phar install --prefer-dist --no-interaction

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyze --no-progress --memory-limit=2G
      
      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit --bootstrap vendor/autoload.php --fail-on-warning tests/phpunit
        
      - name: Run integration tests
        run: ./tests/travis.sh -t4
