name: test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-php:
    name: Prepare PHP
    runs-on: ${{ matrix.image }}

    strategy:
      matrix:
        image: [ubuntu-20.04]
        php: [8.0.23, 8.1.10]

    steps:
      - name: Build and prepare PHP cache
        uses: pmmp/setup-php-action@82a44d659bf5046612c69f036af3e14dc32e3fa8
        with:
          php-version: ${{ matrix.php }}
          install-path: "./bin"

 
  codegen:
    name: Generated Code consistency checks
    needs: build-php
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image: [ubuntu-20.04]
        php: [8.0.23, 8.1.10]

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: pmmp/setup-php-action@82a44d659bf5046612c69f036af3e14dc32e3fa8
        with:
          php-version: ${{ matrix.php }}
          install-path: "./bin"

      - name: Install Composer
        run: curl -sS https://getcomposer.org/installer | php

      - name: Restore Composer package cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/composer/files
            ~/.cache/composer/vcs
          key: "composer-v2-cache-${{ matrix.php }}-${{ hashFiles('./composer.lock') }}"
          restore-keys: |
            composer-v2-cache-

      - name: Install Composer dependencies
        run: php composer.phar install --no-dev --prefer-dist --no-interaction

      - name: Regenerate registry annotations
        run: php build/generate-registry-annotations.php src

      - name: Regenerate KnownTranslation APIs
        run: php build/generate-known-translation-apis.php

      - name: Verify code is unchanged
        run: |
          git diff
          git diff --quiet

  codestyle:
    name: Code Style checks
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP and tools
        uses: shivammathur/setup-php@2.22.0
        with:
          php-version: 8.0
          tools: php-cs-fixer:3.11

      - name: Run PHP-CS-Fixer
        run: php-cs-fixer fix --dry-run --diff --ansi
